# File:         MULTIPASS/STsubloop_X.mac
# Description:  Replicates Scanning table motion
#
# Version:      1.0.0
# Created:      2020-03-18
# Author:       Michael Hubbard
# Modified:     
#
#
# Tested with:
#              Geant4 v 10.4.p01
#              ROOT v 6.12.06
#
# ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......
#

# STsubloop_X.mac

/MULTIPASS/gun/ScanTableX {xoffset}  

/run/beamOn 10000
